accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

pages/urls.py
from django.urls import path

from .views import HomePageView, TaskPageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path('tasks/', TaskPageView.as_view, name="tasks")
]

taskeeper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts", include("django.contrib.auth.urls")),
    path("tasks/", include("tasks.urls")),
    path("", include("pages.urls")),
    path("tasks", TemplateView.as_view(template_name="home.html"),
         name="home"),
    path("", TemplateView.as_view(template_name="home.html"),
         name="home"),

]

tasks/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.TaskListView.as_view(), name='task_list'),
    path('task/<int:pk>/', views.TaskDetailView.as_view(), name='task_detail'),
    path('task/new/', views.TaskCreateView.as_view(), name='new_task'),
    path('task/<int:pk>/edit/', views.TaskUpdateView.as_view(), name='task_edit'),
    path('task/<int:pk>/delete/', views.TaskDeleteView.as_view(), name='task_delete'),
    path('completed/', views.CompletedTaskListView.as_view(), name='completed_task_list'),
    path('task/<int:task_id>/mark_completed/', views.mark_task_completed, name='mark_completed'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=True)

pages/models.py
from django.db import models

# Create your models here.

tasks/models.py
# models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Task(models.Model):
    CATEGORY_CHOICES = (
        ('personal', 'Personal'),
        ('work', 'Work'),
        ('shopping', 'Shopping'),
        ('miscellaneous', 'Miscellaneous'),
    )
    PRIORITY_CHOICES = (
        ('high', 'High'),
        ('medium', 'Medium'),
        ('low', 'Low'),
        ('completed', 'Completed'),
    )

    title = models.CharField(max_length=255)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default='miscellaneous')
    priority = models.CharField(max_length=20, choices=PRIORITY_CHOICES, default='medium')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("task_detail", kwargs={"pk": self.pk})


class CompletedTask(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    date_completed = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.task} - Completed on {self.date_completed}"

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + (
            "username",
            "email",
            "age",
        )


class CustomerUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = (
            "username",
            "email",
            "age",
        )

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import CustomUserCreationForm


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = "registration/signup.html"

pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "home.html"


class TaskPageView(TemplateView):
    template_name = "task_list.html"

tasks/views.py
# views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import (
    UpdateView, DeleteView, CreateView)
from django.urls import reverse_lazy
from .models import Task, CompletedTask

class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "new_task.html"
    fields = (
        "title",
        "body",
        "category",  # Assuming category field is added to the Task model
        "priority",  # Assuming priority field is added to the Task model
    )
    success_url = reverse_lazy('task_list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "task_list.html"

    def get_queryset(self):
        return Task.objects.filter(author=self.request.user)


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = 'task_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task = context['object']
        completed_tasks = task.completedtask_set.all()
        context['completed_tasks'] = completed_tasks
        return context


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = (
        "title",
        "body",
        "category",
        "priority",
    )
    template_name = "task_edit.html"
    success_url = reverse_lazy('task_list')

    def test_func(self):
        task = self.get_object()
        return task.author == self.request.user


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = "task_delete.html"
    success_url = reverse_lazy("task_list")

    def test_func(self):
        task = self.get_object()
        return task.author == self.request.user


class CompletedTaskListView(LoginRequiredMixin, ListView):
    model = CompletedTask
    template_name = "completed_tasks.html"
    context_object_name = "completed_tasks"  # Define the context variable name

    def get_queryset(self):
        return CompletedTask.objects.filter(task__author=self.request.user)


def mark_task_completed(request, task_id):
    task = Task.objects.get(pk=task_id)
    CompletedTask.objects.create(task=task)
    task.delete()
    return redirect('task_list')

templates/article_detail.html
{% extends "base.html" %}
{% block content %}
<div class="task-entry">
    <h2>{{ object.title }}</h2>
    <p>by {{ object.author }} | {{ object.date }}</p>
    <p>{{ object.body }}</p>
</div>

<p><a href="{% url 'task_edit' task.pk %}">Edit</a> |
    <a href="{% url 'task_delete' article.pk %}">Delete</a></p>
<p>Back to <a href="{% url 'task_list' %}">All Tasks</a>.</p>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Task Manager App{% endblock title %}</title>
     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <header class="p-3 mb-3 border-bottom">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a class="navbar-brand" href="{% url 'home'%}">Task Keeper</a>
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                {% if user.is_authenticated %}
                  <li><a href="{% url 'new_task' %}"
                      class="nav-link px-2 link-dark">+ New Task</a></li>
                  <li><a href="{% url 'task_list' %}"
                      class="nav-link px-2 link-dark">All Tasks</a></li>
                  <li><a href="{% url 'completed_task_list' %}"
                      class="nav-link px-2 link-dark">Completed Tasks</a></li>
                </ul>
                <div class="dropdown text-end">
                        <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle"
                           id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                            <li><a class="dropdown-item" href="{% url 'password_change'%}">Change password</a></li>
                            <li><a class="dropdown-item" href="{% url 'logout'%}">Log Out</a></li>
                        </ul>
                {% else %}
                    <div class="text-end">
                        <a href="{% url 'login' %}" class="btn btn-outline-primary me-2">
                            Log In</a>
                        <a href="{% url 'signup' %}" class="btn btn-primary">Sign Up</a>
                    </div>
                {% endif %}
                </div>
        </div>
    </div>
    </header>
    <main>
        {% block content %}
        {% endblock content %}
    </main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
    </script>
</body>
</html>

templates/completed_tasks.html
<!-- templates/completed_task_list.html -->
{% extends "base.html" %}

{% block title %}Completed Tasks{% endblock title %}

{% block content %}
    <h1>Completed Tasks</h1>
    <ul>
        {% for completed_task in task_list %}
        <li>{{ completed_task.task.title }} - Completed on {{ completed_task.date_completed }}</li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock title %}

{% block content %}
{% if user.is_authenticated %}
    Hi {{ user.username }}!
    {% if user.age %}
    You are {{ user.age }} years old.
    {% endif %}
    <p>See your tasks </p>
    <p><a href="{% url 'tasks' %}">Tasks</a></p>

{% else %}
    <p>You are not logged in</p>
    <a href="{% url 'login' %}">Log In</a> |
    <a href="{% url 'signup' %}">Sign Up</a>
{% endif %}
{% endblock content %}

templates/new_task.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
<h1>New Task</h1>
<form action="" method="post">{% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success ml-2" type="submit">Save</button>
</form>
{% endblock content %}

templates/task_delete.html
{% extends "base.html" %}
{% block content %}
<h1>Delete</h1>
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ task.title }}"?</p>
    <button class="btn btn-danger ml-2"
type="submit">Confirm</button>
</form>
{% endblock content %}

templates/task_detail.html
{% extends "base.html" %}
{% block content %}
<div class="task-entry">
    <h2>{{ object.title }}</h2>
    <p>by {{ object.author }} | {{ object.date }}</p>
    <p>{{ object.body }}</p>
</div>

<p><a href="{% url 'task_edit' task.pk %}">Edit</a> |
    <a href="{% url 'task_delete' task.pk %}">Delete</a></p>
    <p>Back to <a href="{% url 'task_list' %}">All Tasks</a>.</p>
{% endblock content %}

templates/task_edit.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Edit</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form | crispy }}
    <button class="btn btn-info ml-2" type="submit">Update</button></form>
{% endblock content %}

templates/task_list.html
{% extends "base.html" %}

{% block title %}Tasks{% endblock title %}

{% block content %}
    {% for task in task_list %}
        <div class="card">
            <div class="card-header">
                <span class="font-weight-bold">{{ task.title }}</span>
                &middot;
                <span class="text-muted">by {{ task.author }} | {{ task.date }}</span>
                &middot;
                <span class="text-muted">Category: {{ task.get_category_display }}</span>
                &middot;
                <span class="text-muted">Priority: {{ task.get_priority_display }}</span>
            </div>
            <div class="card-body">
                {{ task.body }}
            </div>
            <div class="card-footer text-center text-muted">
                <a href="{% url 'task_edit' task.pk %}">Edit</a> |
                <a href="{% url 'task_delete' task.pk %}">Delete</a> |
                <a href="{% url 'mark_completed' task.pk %}">Mark Completed</a>
            </div>
        </div>
        <br>
    {% endfor %}
{% endblock content %}